kafka 配置

diff --git a/kafka/kafka-chats/templates/config.yaml b/kafka/kafka-chats/templates/config.yaml
--- a/kafka/kafka-chats/templates/config.yaml
+++ b/kafka/kafka-chats/templates/config.yaml
@@ -7,6 +7,19 @@ metadata:
     helm.sh/chart: {{ include "kafka-chats.chart" . }}
     app.kubernetes.io/instance: {{ .Release.Name }}
 data:
+  start-kafka.sh: |+
+    #!/bin/bash
+
+    HOSTNAME="$(hostname -s)"
+    if [[ $HOSTNAME =~ (.*)-([0-9]+)$ ]]; then
+      ORD=${BASH_REMATCH[2]}
+      sed -i 's/{{broker_id}}/$((ORD))/' $KAFKA_HOME/config/server.properties
+    else
+      echo "Failed to get index from hostname $HOSTNAME"
+      exit 1
+    fi
+    $KAFKA_HOME/bin/kafka-server-start.sh $KAFKA_HOME/config/server.properties
+
   server.properties: |
     # Licensed to the Apache Software Foundation (ASF) under one or more
     # contributor license agreements.  See the NOTICE file distributed with
@@ -31,7 +44,7 @@ data:
     ############################# Server Basics #############################
 
     # The id of the broker. This must be set to a unique integer for each broker.
-    broker.id=0
+    broker.id={{broker_id}}
 
     ############################# Socket Server Settings #############################
 
@@ -41,11 +54,15 @@ data:
     #     listeners = listener_name://host_name:port
     #   EXAMPLE:
     #     listeners = PLAINTEXT://your.host.name:9092
-    #listeners=PLAINTEXT://:9092
+    # listeners=PLAINTEXT://{{ include "kafka-chats.fullname" . }}:9092
 
     # Listener name, hostname and port the broker will advertise to clients.
     # If not set, it uses the value for "listeners".
-    #advertised.listeners=PLAINTEXT://your.host.name:9092
+    # advertised.listeners=PLAINTEXT://{{ include "kafka-chats.fullname" . }}:9092
+    listener.security.protocol.map=INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
+    inter.broker.listener.name=INSIDE
+    listeners=INSIDE://my-kafka-kafka-chats-0:9092,OUTSIDE://my-kafka-kafka-chats-0:9094
+    advertised.listeners=INSIDE://my-kafka-kafka-chats-0:9092,OUTSIDE://node1:32452
 
     # Maps listener names to security protocols, the default is for them to be the same. See the config documentation for more details
     #listener.security.protocol.map=PLAINTEXT:PLAINTEXT,SSL:SSL,SASL_PLAINTEXT:SASL_PLAINTEXT,SASL_SSL:SASL_SSL
