zeppelin docker

diff --git a/zeppelin/images/Dockerfile b/zeppelin/images/Dockerfile
--- a/zeppelin/images/Dockerfile
+++ b/zeppelin/images/Dockerfile
@@ -1,3 +1,18 @@
+# Licensed to the Apache Software Foundation (ASF) under one or more
+# contributor license agreements.  See the NOTICE file distributed with
+# this work for additional information regarding copyright ownership.
+# The ASF licenses this file to You under the Apache License, Version 2.0
+# (the "License"); you may not use this file except in compliance with
+# the License.  You may obtain a copy of the License at
+#
+#    http://www.apache.org/licenses/LICENSE-2.0
+#
+# Unless required by applicable law or agreed to in writing, software
+# distributed under the License is distributed on an "AS IS" BASIS,
+# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
+# See the License for the specific language governing permissions and
+# limitations under the License.
+
 FROM ubuntu:20.04
 
 LABEL maintainer="Apache Software Foundation <dev@zeppelin.apache.org>"
@@ -14,28 +29,58 @@ ENV LOG_TAG="[ZEPPELIN_${Z_VERSION}]:" \
 
 RUN echo "$LOG_TAG install basic packages" && \
     apt-get -y update && \
+    # Switch back to install JRE instead of JDK when moving to JDK9 or later.
     DEBIAN_FRONTEND=noninteractive apt-get install -y --fix-missing \
-    net-tools curl vim locales language-pack-en tini \
-    openjdk-8-jdk-headless openjdk-8-jre-headless wget unzip python3.6 && \
+    net-tools curl vim locales language-pack-en tini openjdk-8-jdk-headless openjdk-8-jre-headless wget unzip && \
     # Cleanup
     rm -rf /var/lib/apt/lists/* && \
     apt-get autoclean && \
     apt-get clean
 
+# Install conda to manage python and R packages
+ARG miniconda_version="py37_4.9.2"
+# Hashes via https://docs.conda.io/en/latest/miniconda_hashes.html
+ARG miniconda_sha256="79510c6e7bd9e012856e25dcb21b3e093aa4ac8113d9aa7e82a86987eabe1c31"
+# Install python and R packages via conda
+COPY env_python_3_with_R.yml /env_python_3_with_R.yml
+COPY Miniconda3-py37_4.9.2-Linux-x86_64.sh /Miniconda3-py37_4.9.2-Linux-x86_64.sh
+
+RUN set -ex && \
+    mv /Miniconda3-py37_4.9.2-Linux-x86_64.sh miniconda.sh && \
+    echo "${miniconda_sha256} miniconda.sh" > anaconda.sha256 && \
+    sha256sum --strict -c anaconda.sha256 && \
+    bash miniconda.sh -b -p /opt/conda
+
+RUN export PATH=/opt/conda/bin:$PATH && \
+    conda config --set always_yes yes --set changeps1 no && \
+    conda install mamba -c conda-forge && \
+    mamba env update -f /env_python_3_with_R.yml --prune && \
+    # Cleanup
+    rm -v miniconda.sh anaconda.sha256  && \
+    # Cleanup based on https://github.com/ContinuumIO/docker-images/commit/cac3352bf21a26fa0b97925b578fb24a0fe8c383
+    find /opt/conda/ -follow -type f -name '*.a' -delete && \
+    find /opt/conda/ -follow -type f -name '*.js.map' -delete && \
+    mamba clean -ay
+    # Allow to modify conda packages. This allows malicious code to be injected into other interpreter sessions, therefore it is disabled by default
+    # chmod -R ug+rwX /opt/conda
+ENV PATH /opt/conda/envs/python_3_with_R/bin:/opt/conda/bin:$PATH
+
 COPY zeppelin-0.11.0-SNAPSHOT.tar.gz /tmp/zeppelin-0.11.0-SNAPSHOT.tar.gz
 
 RUN echo "$LOG_TAG Download Zeppelin binary" && \
     mkdir -p ${ZEPPELIN_HOME} && \
-    tar --strip-components=1 -zxvf  /tmp/zeppelin-0.11.0-SNAPSHOT.tar.gz -C ${ZEPPELIN_HOME} && \
-    rm -f /tmp/zeppelin-0.11.0-SNAPSHOT.tar.gz && \
-    chown -R root:root ${ZEPPELIN_HOME} && \
+    tar --strip-components=1 -zxf  /tmp/zeppelin-0.11.0-SNAPSHOT.tar.gz -C ${ZEPPELIN_HOME} && \
+    rm -f /tmp/zeppelin-0.11.0-SNAPSHOT.tar.gz
+
+RUN chown -R root:root ${ZEPPELIN_HOME} && \
     mkdir -p ${ZEPPELIN_HOME}/logs ${ZEPPELIN_HOME}/run ${ZEPPELIN_HOME}/webapps && \
     # Allow process to edit /etc/passwd, to create a user entry for zeppelin
     chgrp root /etc/passwd && chmod ug+rw /etc/passwd && \
     # Give access to some specific folders
     chmod -R 775 "${ZEPPELIN_HOME}/logs" "${ZEPPELIN_HOME}/run" "${ZEPPELIN_HOME}/notebook" "${ZEPPELIN_HOME}/conf" && \
     # Allow process to create new folders (e.g. webapps)
-    chmod 775 ${ZEPPELIN_HOME}
+    chmod 775 ${ZEPPELIN_HOME} && \
+    chmod -R 775 /opt/conda
 
 COPY log4j.properties ${ZEPPELIN_HOME}/conf/
 COPY log4j_docker.properties ${ZEPPELIN_HOME}/conf/
@@ -48,5 +93,4 @@ EXPOSE 8080
 
 ENTRYPOINT [ "/usr/bin/tini", "--" ]
 WORKDIR ${ZEPPELIN_HOME}
-
 CMD ["bin/zeppelin.sh"]
